name: gee
channels:
  - defaults
  - conda-forge
dependencies:
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - geojson=2.5.0=py_0
  - geopandas=0.11.1=pyhd8ed1ab_0
  - geopandas-base=0.11.1=pyha770c72_0
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - pandas=1.4.3
  - plotly=5.9.0=pyhd8ed1ab_0
  - streamlit=1.11.1=pyhd8ed1ab_0
  - streamlit-folium=0.6.14=pyhd8ed1ab_0